version: "2"
services:
  cli:
    build: ./cli
    command: ["/bin/sleep", "infinity"]
    image: storj-cli
  db:
    image: mongo:3.4.0
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - "27017"
  mq:
    image: rabbitmq:3.6.6
  bridge:
    build: ./bridge
    volumes:
      - ./bridge/config.json:/bridge/config.json
    command: ["./bin/storj-bridge.js", "-c", "/bridge/config.json"]
    environment:
      - DOCKER_SERVICES=db:27017
    ports:
      - "8080"
  landlord:
    build: ./complex
    volumes:
      - ./complex/landlord.config.json:/root/config.template.json
    command: ["./bin/storj-complex.js", "-c", "/root/config.json"]
    environment:
      - DOCKER_SERVICES=bridge:8080,db:27017,mq:5672
  renter:
    build: ./complex
    volumes:
      - ./complex/renter.config.json:/root/config.template.json
      - ./complex/hd-private.key:/root/hd-private.key
    command: ["./bin/storj-complex.js", "-c", "/root/config.json"]
    environment:
      - DOCKER_SERVICES=bridge:8080,db:27017,mq:5672
    restart: always
    ports:
      - "4000"
  share:
    build: ./share
    volumes:
      - ./share/instances:/share/instances
      - ./share/templates:/share/templates
      - ./vendor:/usr/src/vendor
    environment:
      - DOCKER_SERVICES=renter:4000
      - affinity:container!=/cadvisor/
    ports:
      - "9000"
  proxy:
    build: ./vpn
    ports:
      - "127.0.0.1:13194:13194"
    command: TCP-LISTEN:13194,fork TCP:172.17.0.1:1194
  openvpn:
    build: ./vpn/openvpn
    volumes:
      - ./vpn:/local
      - ./vpn/config:/etc/openvpn
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      dest: storj-local.ovpn
      DEBUG: '1'
      DOCKER_NETWORK: storjsdk_default
    command: ["/local/helpers/run.sh"]
  bridge-gui:
    build: ./bridge-gui/bridge-gui
    ports:
      - "8080"
    environment:
      - APIHOST_VAL=bridge-ssl-proxy
      - APIPORT_VAL=443
      - APIPROTOCOL_VAL=https
      - NODE_ENV_VAL=production
      - STRIPE_PUBLISHABLE_KEY_VAL=pk_test_3jNyjwE39k9y2EbKpIM0Ilz1
      - APOLLO_CLIENT_URL_VAL=https://bridge-gui-ssl-proxy:3000/graphql
      - OUTPUT_PUBLIC_PATH_PROTOCOL_VAL=https
      - OUTPUT_PUBLIC_PATH_URL_VAL=bridge-gui-ssl-proxy
    command: ["./dockerfiles/scripts/start-bridge-gui"]
  bridge-gui-ssl-proxy:
    image: storjlabs/nginx-ssl-proxy:latest
    environment:
      - ENABLE_SSL=true
      - TARGET_SERVICE=bridge-gui:8080
    ports:
      - "443"
    volumes:
      - ./bridge-gui/dockerfiles/scripts/certs.dev/cert.pem:/etc/secrets/tls.crt
      - ./bridge-gui/dockerfiles/scripts/certs.dev/key.pem:/etc/secrets/tls.key
      - ./bridge-gui/dockerfiles/scripts/certs.dev/dhparams.pem:/etc/secrets/tls.dhparam
  bridge-ssl-proxy:
    image: storjlabs/nginx-ssl-proxy:latest
    environment:
      - ENABLE_SSL=true
      - TARGET_SERVICE=bridge:8080
    ports:
      - "443"
    volumes:
      - ./bridge-gui/dockerfiles/scripts/certs.dev/cert.pem:/etc/secrets/tls.crt
      - ./bridge-gui/dockerfiles/scripts/certs.dev/key.pem:/etc/secrets/tls.key
      - ./bridge-gui/dockerfiles/scripts/certs.dev/dhparams.pem:/etc/secrets/tls.dhparam
